services:

  backend:
    image: arthurcidqal/smilehub-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.0.0.4:5432/smilehub
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - network_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.smilehub-backend.rule=Host(`av3.com.br`) && PathPrefix(`/smilehub/api`)"
        - "traefik.http.routers.smilehub-backend.entrypoints=websecure"
        - "traefik.http.routers.smilehub-backend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.smilehub-backend.loadbalancer.server.port=8080"

  frontend:
    image: arthurcidqal/smilehub-frontend:latest
    networks:
      - network_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.smilehub-frontend.rule=Host(`av3.com.br`) && PathPrefix(`/smilehub`)"
        - "traefik.http.routers.smilehub-frontend.entrypoints=websecure"
        - "traefik.http.routers.smilehub-frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.smilehub-frontend.loadbalancer.server.port=80"

networks:
  network_public:
    external: true
