services:

  backend:
    image: arthurcidqal/smilehub-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.0.0.4:5432/smilehub
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    image: arthurcidqal/smilehub-frontend:latest
    ports:
      - "3000:80"
