spring.application.name=smilehub
# porta padrão 
server.port=8090
server.tomcat.uri-encoding=UTF-8

server.servlet.context-path=/smilehub

# URL de conexão
spring.datasource.url=jdbc:mysql://localhost:3306/smilehub?useSSL=false&serverTimezone=UTC

# Credenciais
spring.datasource.username=root
spring.datasource.password=master100

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect